### ISSUE TITLE
When calculating the average estimate, the results value is lower than the manually calculated results value

### ISSUE THREAD

**Issue by romoy** [websdotcom/BitPoints#27]
When calculating the average estimate, the results value is lower than the manually calculated results value.

e.g.
Observed:
Vote of (8, 8, 8, 13) / 4 results in 7.80 or a ceiling of 8.

Expected
Vote of (8,8,8,13) / 4 should result in 9.25 or a ceiling of 10.

**Comment by jackwanders** [comment]
Fixed in #29

**Comment by romoy** [comment]
Awesome @jackwanders!! Thank you!!
